DROP TABLE IF EXISTS fines;

CREATE TABLE IF NOT EXISTS fines (
id INTEGER PRIMARY KEY AUTO_INCREMENT,
carNum VARCHAR(255)NOT NULL  ,
regNum VARCHAR(255)NOT NULL,
dateOfFine VARCHAR(255) NOT NULL,
info VARCHAR(255) NOT NULL DEFAULT 0,
price INTEGER NOT NULL
);